# Generated by Django 4.1.2 on 2022-10-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('FolderId', models.AutoField(primary_key=True, serialize=False)),
                ('FolderName', models.CharField(max_length=500)),
                ('ParentFolderId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('TopicId', models.AutoField(primary_key=True, serialize=False)),
                ('TopicName', models.CharField(max_length=500)),
                ('Folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalDocs.folders')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('DocId', models.AutoField(primary_key=True, serialize=False)),
                ('DocName', models.CharField(max_length=500)),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalDocs.topics')),
            ],
        ),
    ]
